# Generated by Django 2.1.7 on 2019-03-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
